const WINDOW_WIDTH = 720;
const WINDOW_HEIGHT = 900;

const GROUND_LINE = 80;
const GROUND_DEPTH = 20;
const GROUND_LEFT_BOUND = 50;
const MAX_PUDDLE_RADIUS = 50;
const MAX_PUDDLE_COUNT = 30;

const ROOT_THICKNESS= 4;
const CURSOR_SPEED = 5;
const DEG_2_RAD = 0.0174533;
const ROOT_WANDER = 45;
const ROOT_SPEED = 5;

const LEVEL_SCALE = 250;
const WATER_DECAY = 0.1;
const DEATH_SPEED = 0.3;

const KEYS = {
  A: 65,
  D: 68,
  S: 83,
  W: 87,
  J: 74,
  K: 75,
};

module.exports = {
  GROUND_LINE,
  GROUND_DEPTH,
  GROUND_LEFT_BOUND,
  MAX_PUDDLE_RADIUS,
  MAX_PUDDLE_COUNT,
  WINDOW_HEIGHT,
  WINDOW_WIDTH,
  ROOT_THICKNESS,
  CURSOR_SPEED,
  DEG_2_RAD,
  ROOT_WANDER,
  ROOT_SPEED,
  KEYS,
  LEVEL_SCALE,
  DEATH_SPEED,
  WATER_DECAY,
};
